### PR TITLE
preliminary iteration of extracting production credentials

### LINKED ISSUE #109: In production, parse DATABASE_URL to get config values
**Describe the bug**
Occasionally heroku will rotate our database credentials, and update the DATABASE_URL env variable with the new values.  However, in the[ config file we use for migrations](https://github.com/timmyichen/dev-directory/blob/main/server/config/config.js), we read the individual `DB_*` variables, which are _not_ updated.

A `DATABASE_URL` might look something like this:
```
postgres://username:password@host:port/databasename
```

**To Reproduce**
No real reproduction steps since it's happening in production builds.  You can, however, verify it by logging the object that gets exported in that config file.  It should be read when running migrations via `npm run migrate`.

**Expected behavior**
If `process.env.NODE_ENV` is `production`, it should parse the env's `DATABASE_URL` and export the username, password, host, etc values from that string.

**Screenshots**
image

**Desktop (please complete the following information):**
N/A

**Additional context**
Happy to pair with folks on this, let me know if you need help.

### PR DESCRIPTION
**Pull request by windyScripts**
Closes #109 

# Description

Production credentials are to be extracted from DB.URL.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

Please include any screenshots if there are visual changes.

# Checklist:

- [x] Changes have new/updated automated tests, if applicable
- [x] Changes have new/updated docs, if applicable
- [x] I have performed a self-review of my own code
- [x] I have added comments on any new, hard-to-understand code
- [x] Changes have been manually tested
- [ ] Changes generate no new errors or warnings

### CODE REVIEW

File: server/config/config.js [hunk 1]
```diff
@@ -28,8 +28,20 @@ const creds = {
   dialectOptions,
 };
 
+const [username, password, host, port, database] = env.DATABASE_URL.replace(/[/:@]/g, ' ').split(' ').slice(3);
```
Comment (timmyichen) [inline server/config/config.js:31]: this is neat, i dig it - you can use regex in `split` so you can probably just bypass the `replace` 👀 

once you make the change i'll attempt a prod deploy from thsi branch and we'll see how it goes!

Comment (windyScripts) [reply server/config/config.js]: I've made this correction.

**Review by timmyichen — APPROVED** [review]
deploy was successful! thanks for taking it on
